### ISSUE TITLE
widget generator should scaffold out files needed for settings

### ISSUE THREAD

**Issue by tomwayson** [Esri/generator-esri-appbuilder-js#1]
The settings page could just include a text box that allows the user to set the widget tittle/description?

**Comment by jpeterson** [comment]
:+1:

Looks like this should be pretty simple from the docs, and would be a good feature.

https://developers.arcgis.com/web-appbuilder/guide/make-widget-configurable-in-builder.htm

**Comment by tomwayson** [comment]
pull requests welcome! :wink:

**Comment by gavinr** [comment]
Working on this, had a discussion with @tomwayson that having a settings page only makes sense if the user chooses 'yes' to `[x] Config (JSON) file` - so there needs to be TWO new steps:

Currently Existing:
`Which features would you like to include?`
[x] Run inside a panel
[x] Locale (i18n) file
[x] Style (CSS) file
[x] Config (JSON) file
[x] Template (HTML) file

If user chooses yes on `[x] Config (JSON) file`:
`Would you like a settings page? [y/N]` (this will be a https://github.com/SBoudrias/Inquirer.js#confirm----type-confirm-)

If user chooses yes on `[x] Settings page`:
`Which settings page features would you like to include?`
[x] Settings locale (i18n) file
[x] Settings style (CSS) file
[x] Settings template (HTML) file

**Comment by tomwayson** [comment]
:+1:

**Comment by tomwayson** [comment]
resolved in #37
