### ISSUE TITLE
"clean:dist" fails frequently

### ISSUE THREAD

**Issue by btpschroeder** [Esri/generator-esri-appbuilder-js#111]
This happens every 2 or 3 times the script runs:

![clean-dist-fails](https://user-images.githubusercontent.com/19781811/40365489-ad2d7fac-5da2-11e8-8d30-83e4057dcf90.PNG)

`Fatal error: Error watching file for changes: EPERM`

I have to manually trigger a save/re-run when this happens. There doesn't seem to be any real pattern. I'm running the script in Git Bash using the Visual Studio Code built-in terminal.

**Comment by gavinr** [comment]
@btpschroeder thanks for logging this. I have been playing with a setting and have been getting some success. If you go into the `Gruntfile.js` that is generated, and change this line:

`clean: { 'dist': { 'src': 'dist/**' } },`

to this:

`clean: { 'dist': { 'src': 'dist/*' } },`

Does it faill less often for you?

**Comment by btpschroeder** [comment]
Yes, that seems to have fixed the issue entirely! Appreciate the quick response.

**Comment by gavinr** [comment]
Great - thanks. I haven't put this into the project since I didn't know if it was a widespread fix, but with your testing I think we have a valid reason to change the code. I'll leave this open until we land the change. Thanks!
