### ISSUE TITLE
Default (latest) version of grunt-sass 

### ISSUE THREAD

**Issue by adepottey** [Esri/generator-esri-appbuilder-js#116]
The latest version of [grunt-sass 3.0.1](https://github.com/sindresorhus/grunt-sass#usage) requires node 8 and additionally has some syntax changes to the task specification.  I had to install grunt-sass 2.1.0 to use the grunt tasks.

**Comment by gavinr** [comment]
Note: the error I'm getting with `grunt-sass 3.0.1` is this:

`Fatal error: The implementation option must be passed to the Sass task`

I will fix this soon, but wanted to add that here in case anyone is searching for the error

**Comment by gavinr** [comment]
@adepottey thanks for the report. This is fixed in #122. NodeJS v8 or greater is now required for this project if you want to use the SASS preprocessor
