### ISSUE TITLE
baseClass specified in generator is not applied in TypeScript

### ISSUE THREAD

**Issue by kenbuja** [Esri/generator-esri-appbuilder-js#120]
I created a widget and specified a baseClass during the widget generator process. This is using TypeScript during the app generator configuration. However, in the generated code, the baseClass is set as the default "my-widget" and "my-widget-setting" in the ts files, but the correct baseClass is used in the scss files.

**Comment by gavinr** [comment]
@kenbuja thanks for the report. I fixed this in #121 and will release a build to npm shortly.
