### ISSUE TITLE
grunt-babel version issue

### ISSUE THREAD

**Issue by brettlawson** [Esri/generator-esri-appbuilder-js#129]
Starting in an empty directory I used the generator to scaffolds out a application using an existing application in web app builder and then I run the widget generator to scaffold out widget code.   

When I list my packages using npm list --depth=0 I get the following

```
### +-- UNMET PEER DEPENDENCY @babel/core@^7.0.0
+-- babel-core@6.26.3
+-- babel-plugin-transform-es2015-modules-simple-amd@0.3.0
+-- babel-preset-es2015-without-strict@0.0.4
+-- babel-preset-stage-0@6.24.1
+-- esri-wab-build@1.0.1
+-- grunt@1.0.3
+-- grunt-babel@8.0.0
+-- grunt-contrib-clean@2.0.0
+-- grunt-contrib-copy@1.0.0
+-- grunt-contrib-watch@1.1.0
+-- grunt-sass@3.0.2
+-- grunt-sync@0.8.0
`-- node-sass@4.9.4

npm ERR! peer dep missing: @babel/core@^7.0.0, required by grunt-babel@8.0.0
```

and when I try to run grunt I get the output below...

```
Loading "babel.js" tasks...ERROR
>> Error: Cannot find module '@babel/core'
>>  grunt-babel@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'grunt-babel@7'.

Running "watch" task
Waiting...
Fatal error: Task "babel" not found.
```
So I downgrade grunt-babel with npm install grunt-babel@7 and then ran grunt and my files where copied over and it work.

Why was grunt-babel@8.0.0 being installed?

**Comment by gavinr** [comment]
This was fixed in https://github.com/Esri/generator-esri-appbuilder-js/releases/tag/v4.2.1 - let us know if you're still having issues.
