### ISSUE TITLE
Add version to build zip file

### ISSUE THREAD

**Issue by sevenninety** [Esri/generator-esri-appbuilder-js#140]
I believe a useful addition to the build process would be to version the app.zip file that is generated.

From package.json the `name` and `version` elements could be used to generate a unique name of the zip file, rather than app.zip, something like:

`myappname-1.0.0.zip`

The `version` in package.json could also be bumped as part of the build process.

For Production that would allow better control of releasing versioned software, driven by the package.json file.

**Comment by gavinr** [comment]
I like this idea, but I'm not sure if it would be implemented here or in the project that we use to do the build, https://github.com/gbochenek/esri-wab-build - @gbochenek may have some insight.

**Comment by gbochenek** [comment]
Agreed.  This would be a great contribution, and I don't think it would be complicated to implement if you wanted to take a stab at it.

Can you create this is on https://github.com/gbochenek/esri-wab-build? We can talk about implementation options over there.  Thanks!
