### ISSUE TITLE
has anyone tried this lately?

### ISSUE THREAD

**Issue by Nathan187** [Esri/generator-esri-appbuilder-js#153]
this looks very promising and I'd like to use it.  however...i can't get this to work.  when i click on the widget, it just "hangs"

has anyone tried this lately?  i'm using the latest version of web app builder

![Screen Shot 2020-03-10 at 9 37 42 AM](https://user-images.githubusercontent.com/1022238/76323578-e2621180-62b2-11ea-9463-f21130219409.png)

**Comment by gavinr** [comment]
Hi Nathan, a few debugging steps:

1. Try creating a widget without a dash in the name - I haven't tried that recently and it's possible that there may be an issue with that.
2. If you try to open one of those files in a new tab - do they load ok?
    ![image](https://user-images.githubusercontent.com/209355/76324606-489b6400-62b4-11ea-828b-59fc9cf9592a.png)

**Comment by Nathan187** [comment]
hello, thank for such a quick reply!

i have been messing with this since yesterday.  the first time i tried it, i did not use a "-" in the name.  same result

i tried opening those links in new tabs...did not work Cannot GET error(s)

i first tried using typescript and then i tried es2015

as you already know, i'm not an expert with this stuff.   thanks for the response/help

**Comment by gavinr** [comment]
Nathan, if the Widget.js file is not loading, I think that is probably not related to the generator and more a general environment issue.

**Comment by Nathan187** [comment]
not sure if this has much to do with anything...but when i try to create a widget through the generator and using typescript.....the file widget.ts is created.  however when trying to use in a map...it appears as if it's trying to find widget.js by default.

**Comment by Nathan187** [comment]
thanks for trying to help.  i wasn't compiling my .ts class.  i tried that and it still didn't work when i copied the js file over...however, i will keep at it

**Comment by Nathan187** [comment]
@gavir Thanks for your help/patience
@DK my coworker who helped with this as well

i somewhat got it to work.  these are the steps i did....maybe it will help someone


(after completing the 'yo esri-appbuilder-js:widget' command)

(in iTerm / console)
after the scaffolding has completed, switch to the {root folder}\widgets\MyWidget folder

during scaffolding, i selected to use typescript...so I did a compile by entering the command '**_tsc_**' at the command prompt

this will create a folder called 'dist'....located at {root folder}\dist

this will create 3 items in the {root folder}\dist\widgets\MyWdiget folder...(config.js, Widget.js and a folder named support)

copy contents of 
{root folder}\dist\widgets\MyWidget
to
{root folder}\widgets\MyWidget  (do not overwrite the support folder...merge the contents)

manually copy the folder {root folder}\widgets\MyWidget to
{webappbuilder location}\client\stemapp\widgets  
and
{webappbuilder location}\server\apps\{app ID}\widgets  

edit the grunt file ({root folder}\Gruntfile.js) to point to your (desired) app location.  edit line 8 and possibly 18

refresh browser

**Comment by dk** [comment]
Hi there, I’m not your colleague but I indeed can gently tell to RTFM for a reasonable price 🤣
