### ISSUE TITLE
Widgets in template

### ISSUE THREAD

**Issue by davewilton** [Esri/generator-esri-appbuilder-js#154]
Just spent an hour scratching my head on this one. If you add templated widgets to your html e.g.

```
auto;">
    <div data-dojo-type="dijit/layout/AccordionPane" title="pane #1">accordion pane #1</div>
    <div data-dojo-type="dijit/layout/AccordionPane" title="pane #2">accordion pane #2</div>
    <div data-dojo-type="dijit/layout/AccordionPane" title="pane #3">accordion pane #3</div>
</div>
```

You both need to mix in the template:
```
@declare(BaseWidget, _WidgetsInTemplateMixin)
class Widget implements IWidget {
```

AND call the startup of _WidgetsInTemplateMixin

```
 public startup(args: any): void {
    BaseWidget.prototype.startup.call(this, args);
    _WidgetsInTemplateMixin.prototype.startup.call(this, args);
```

Another option is not to use strict mode in your tsconfig  "noImplicitUseStrict": true which then allows:

```
 public startup(args: any): void {
    var self: any = this;
    this.inherited(arguments);
```

This should probably be added to the documentation (easiest) or we add a new option "will your widget contain templated dojo widgets" which stubs this out

**Comment by gavinr** [comment]
@davewilton thank you for this - I will propose a change to the documentation that notes this.

**Comment by gavinr** [comment]
@davewilton do you think the changes proposed in #155 covers it well enough?

**Comment by davewilton** [comment]
@gavinr yes looks good
