### ISSUE TITLE
Experience Builder version

### ISSUE THREAD

**Issue by gavinr** [Esri/generator-esri-appbuilder-js#158]
What about Experience Builder?

This Yeoman Generator for [Web AppBuilder](https://developers.arcgis.com/web-appbuilder/) does two things:

1. It creates a Grunt-based build process for your widgets that watches your source code and every time you change it builds your TypeScript or ES6 code (using the TypeScript compiler or babel, respectively)) and copies it to the Web AppBuilder folder structure.
2. It generates all the files for a widget for you given a command (`yo esri-appbuilder-js:widget`).

For [Experience Builder](https://developers.arcgis.com/experience-builder/), those are now accomplished through:

1. The build process for Experience Builder widgets now comes out-of-the-box in Developer Edition of Experience Builder. You simply run `npm start` within the `client` folder, and that will run a webpack task that will watch your code, build it (using webpack, TypeScript, and React), and make it available for use. [More info](https://developers.arcgis.com/experience-builder/guide/install-guide/#client)
2. You can now generate all the files for an Experience Builder widget using the [arcgis-js-cli](https://github.com/Esri/arcgis-js-cli) project. See that link for detailed instructions, but the general instructions are:
   1. `npm install -g @arcgis/cli`
   1. `cd C:\path\to\experience-builder\root\folder`
   1. `arcgis widget my-widget -t exb`

GeoNet for questions and help on this: https://community.esri.com/community/arcgis-experience-builder

**Comment by rstevens354** [comment]
@gavinr is there a generator for layouts in Experience Builder

**Comment by gavinr** [comment]
@rstevens354 I'm not sure exactly what you mean by "layouts" ... are you referring to [custom themes](https://developers.arcgis.com/experience-builder/guide/theme-development/)?
