### ISSUE TITLE
 a hello world sample

### ISSUE THREAD

**Issue by Nathan187** [Esri/generator-esri-appbuilder-js#159]
does anyone have a hello world type sample to demonstrate how to use this?

for example, something like getting the current user
https://developers.arcgis.com/labs/javascript/access-services-with-oauth-2/

anything...that shows how to use other esri libraries (portal, mapview, oauthinfo), etc.  
thanks in advance

**Comment by gavinr** [comment]
HI @Nathan187, this library is a helper for advanced development workflows related to custom Web AppBuilder widgets. For help on how you can build widgets, you should look at the resources on https://developers.arcgis.com/web-appbuilder, (see `Guide > Widget Development`). You might also check out this video: https://www.youtube.com/watch?v=MKEIvRlybC4

**Comment by Nathan187** [comment]
thank you for your time.  i'm sorry for it appears i wasted it

**Comment by gavinr** [comment]
no problem! We're happy to help!

**Comment by Nathan187** [comment]
for what it worth...following the simple instructions for this...if you are not using typescript...if you are using ES or ES2015....when you deploy it, it does not work.  (when you deploy the widget and then click on it...a blank window appears with an ok button)...if you use typescript it works fine.  i know i stated earlier about samples and am aware how new i am to this...but code fragments (i.e _WidgetsInTemplateMixin) don't help....that's why i had asked for a hello world sample...code fragments aren't enough

**Comment by gavinr** [comment]
@Nathan187 what code fragments are you referring to? If this tools is not working when you use ES or ES2015, please open a new issue with replication steps and we're happy to look into it.
