### ISSUE TITLE
Offer option to generate ES6 files

### ISSUE THREAD

**Issue by tomwayson** [Esri/generator-esri-appbuilder-js#32]
Instead of using grunt sync/copy to copy ES5 files from the working folder to the WAB, we could work in ES6 and use grunt babel to transpile the code and output to the WAB folder.

This should happen after #28

**Comment by tomwayson** [comment]
Note that the babel config options need to be set in the app generator. Need to figure out if we would also offer this option in the widget subgenerator (i.e. a user can develop both es5 or es6 widgets w/in a single project). If that complicates things at all, I say no.

**Comment by gavinr** [comment]
Working on this:

Switching over to the ES2015-compatible Gruntfile should work with either ES2015 or ES5 style widgets, so current plan is to have the question of "ES2015 or ES5" style be at the widget subgenerator level. 

Question of which `jshintrc` file to use will be addressed in a separate item (#56).
