### ISSUE TITLE
Drop theme sub generator?

### ISSUE THREAD

**Issue by tomwayson** [Esri/generator-esri-appbuilder-js#38]
Is anyone using this? @spohner, @g3r4n, @jPurush, @gavinr? Seems like the normal practice for creating a custom theme is to copy an existing one that is closest to the one you want to create. So I'm not sure that a generator based on a single theme even makes much sense.

Furthermore, there's an open bug #33 that I have no plan to fix, and I don't know of any contributors that are interested in maintaining the theme generator. This means it will be hard to continue to evolve this repo as long as we have to continue to work around the broken theme generator.

One idea is to consider merging #36 as a v2 (it requires a bump in the version of the yeoman-generator dependency to at least v0.17) - at which point we could make breaking changes, including dropping the theme.

cc @yiweima, @asizer, @qlqllu

**Comment by g3r4n** [comment]
I'm not using it i'm just using the widget generator. It 'is possible to made the widgets folder configurable ?

**Comment by spohner** [comment]
Not using it anymore. The most important and used functionality is the widget generator. I do not disagree on dropping the theme generator.

**Comment by tomwayson** [comment]
@spohner, @g3r4n thank you both for weighing in. 

I really appreciate your efforts in creating and updating the theme generator - it is a much more complex generator than the widget generator, and must have been a significant undertaking. 

However, it sounds like we all agree that it is not worth the effort to maintain, so I'm planning to drop it for [v2](https://github.com/Esri/generator-esri-appbuilder-js/milestones/v2.0).

**Comment by asizer** [comment]
noooooooooo, come baaaaaaack! :anguished:
