### ISSUE TITLE
Widget generator should populate auth/org/lic properties from app's package.json (if exists)

### ISSUE THREAD

**Issue by tomwayson** [Esri/generator-esri-appbuilder-js#4]
If the user has created a `package.json` file in the (stem)app root folder, either by running the app (default) generator or by hand, then we can populate the following properties in `manifest.json`:
- author
- copyright
- license

**Comment by tomwayson** [comment]
As mentioned in #5 better way to do this is probably using a .yo-rc file

**Comment by gavinr** [comment]
In the basic `package.json`, I don't see "copyright" as a property ... should we just populate "copyright" with the "author"?

Also a small note: looks like in the [package.json spec](https://docs.npmjs.com/files/package.json#people-fields-author-contributors), `author` could be either a string or object, where WAB `maifest` [only supports a string](https://developers.arcgis.com/web-appbuilder/guide/widget-manifest.htm). I would propose following what NPM is doing in the documentation, and in the case that there is also `email` and `url` properties, append them like so:

> Barney Rubble <b@rubble.com> (http://barnyrubble.tumblr.com/)

There can also be a `contributors` property, but I think we should avoid that and only handle the `author` property of `package.json`, at least for now

**Comment by tomwayson** [comment]
Fully agree as far as author goes - don't worry about contributors.

Didn't realize that copyright wasn't a packge.json field.. I'd go w/ current year, or just leave it empty.
