### ISSUE TITLE
Base on yeoman-generator v0.18

### ISSUE THREAD

**Issue by tomwayson** [Esri/generator-esri-appbuilder-js#42]
Since v2.0.0 is a breaking change, might as well be on latest ver of yeoman-generator. Also, there is a very *slight* chance that we'll need this for #39. 

Even if not, I'm almost certain that we'll want it for v2.1 so the default generator can store the user's ES6 preference for later use in the widget generator. So if this does not happen for v2.0 it will go into v2.1.

See the [v0.18 blog post](http://yeoman.io/blog/release-0.18.html) for info.

**Comment by tomwayson** [comment]
um.. so I guess there's been [a lot more yeoman generator releases since 0.17](https://github.com/yeoman/generator/releases). In particular, the release notes for 0.19 lead me to believe that they are headed towards a stable 1.0 release, and from what I can see in subsequent deprecation releases (0.20, etc), they are planning on changing a lot. Just upgrading our code base from 0.17 to 0.18 had issues, and now I'm trying to go straight to the latest (0.22) and it's a major overhaul - enough that I want to tackle it as part of a major release of this repo.

So, the question is, do we release 2.0 as is, and plan for a 3.0 release when yeoman-generator v1.0.0 comes out, or do we at least update to 0.22 right now to make a later update easier. Only reason I want to do the latter is that it is going to make #32 a better experience for users.

@gavinr, thoughts?

**Comment by gavinr** [comment]
@tomwayson seems like a matter of how much additional work it is ... I agree that updating to 0.22 would be great so we can then get to #32. What level of "overhaul" are we talking here?

**Comment by tomwayson** [comment]
So, I went ahead and updated the main generator and it's tests. Only a few lines had to change in the actual generator code (app/index.js), however the tests required a significant overhaul (overall reduction in LOC) of the test file:

```bash
git diff HEAD^ --stat
 app/index.js          |   7 +--
 package.json          |  15 +++---
 test/test-creation.js | 138 +++++++++++++++-----------------------------------
 widget/index.js       |   4 +-
 4 files changed, 53 insertions(+), 111 deletions(-)
```

I'm going to give the widget generator a go. Hopefully I've come across most of the pain points already. I'd recommend holding off on branching/updating for a day or so until I can PR this.

**Comment by gavinr** [comment]
:+1:
