### ISSUE TITLE
add ability to generate 3d widgets

### ISSUE THREAD

**Issue by tomwayson** [Esri/generator-esri-appbuilder-js#46]
Look at structure of 3d widgets in WAB 2.0 beta for differences (prob more than just the 2d/3d setting in manifest), and add a prompt that let's user choose 2/d/3d.

**Comment by tomwayson** [comment]
Once #52 is implemented, need to:
- read stored 2d/3d setting, and if 3d
- update manifest.json template to output changes for 3d (platform, etc), see #50 and #49

**Comment by tomwayson** [comment]
FYI - according to the docs that come embedded in WAB 2.0beta, these are the only diffs between 2d/3d widgets:

3D widget development

> The 3D widget is almost the same as the 2D widget. As a result, you can follow the 2D widget development guide to create a 3D widget.
> 
> As the map property is replaced by sceneView, use this.sceneView to access the scene view in your widget.
>     Put your widget in stemapp3d/widgets folder.
>     In the widget manifest.json file, set “platform”: “HTML3D”.
>     Use ArcGIS API for Javascript 4.0 to develop 3D widgets at runtime while use 3.15 to create 3D widgets setting page in the builder.

So I'm assuming there are no changes in the WAB widget lifecycle methods, any of the other manifest.json properties (still looking into #49), nor any of the other conventions around widget file names, content (including the settings pages files).

**Comment by jPurush** [comment]
There are a couple of other things that could be addressed here: 

1. the serviceurl in the widget's config.json is not applicable in the 3d scenario
2. the version and wabversion is set to 1.4 by default in manifest.json template. should it reflect the wabroot value automatically or be a prompt?

**Comment by tomwayson** [comment]
Closed by #54
