### ISSUE TITLE
support for new manifest.json properties

### ISSUE THREAD

**Issue by jPurush** [Esri/generator-esri-appbuilder-js#49]
keepConfigAfterMapSwitched, hasVersionManager and supportMultiInstance need to be added to the features list

**Comment by tomwayson** [comment]
thanks @jPurush - what version of WAB did these get introduced in? 2.0beta, or earlier?

**Comment by jPurush** [comment]
_keepConfigAfterMapSwithched_(this is the spelling in WAB) and _hasVersionManager_ is available from WAB 1.0, _supportMultiInstance_ is available from WAB 1.3

**Comment by tomwayson** [comment]
Interesting. I've never heard of any of these. I don't know how their used, so it's hard to say whether it's worth adding them to the widget options prompt, what we should use as defaults, and what other impacts (if any) they would have other than setting manifest.json props.

Do you know? Have you ever used them in an app?

**Comment by gavinr** [comment]
Closing this for now, as there has been no interest in these properties in 1.5 years. Developers can manually add if they need these (https://developers.arcgis.com/web-appbuilder/guide/widget-manifest.htm), and we can re-open this if anyone has any particular interest in these manifest properties.
