### ISSUE TITLE
change initial instructions?

### ISSUE THREAD

**Issue by asizer** [Esri/generator-esri-appbuilder-js#53]
This is the instructions when running `yo esri-appbuilder-js`:
> The generators should be run in the root folder of either the stem app or an app that you've already created with the Web AppBuilder.

But this is from the readme:
> The generators should be run in the root of a working folder for your project. This should be outside of the Web AppBuilder's folder structure (**i.e. NOT in the stem app or an app that you've already created with the Web AppBuilder**). The grunt tasks configured by the generators will handle copying the widget files to the appropriate folders under the Web AppBuilder's install directory.

**Comment by tomwayson** [comment]
Thanks! This has been [changed in master](https://github.com/Esri/generator-esri-appbuilder-js/blob/3c3aa9a9a50bd3ae724ad2aa8e8bdb3e7df694c9/app/index.js#L34), which will be released soon. Then the instructions in the README will be in sync w/ the prompts.
