### ISSUE TITLE
Missing mkdirp dependency

### ISSUE THREAD

**Issue by tomwayson** [Esri/generator-esri-appbuilder-js#59]
Installing this on a clean machine it appears that mkdirp is not installed. I think it will be if it's moved from devDependencies to dependencies.

**Comment by gavinr** [comment]
nice find tom :+1:

**Comment by tomwayson** [comment]
Thx. Hope no one else "found" it.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Fri, Mar 4, 2016 at 6:08 AM -0800, "Gavin Rehkemper" <notifications@github.com<mailto:notifications@github.com>> wrote:


nice find tom [:+1:]

-
