### ISSUE TITLE
Grunt option to do a Dojo build of WAB

### ISSUE THREAD

**Issue by gavinr** [Esri/generator-esri-appbuilder-js#62]
We could build into our gruntfile, in addition to the "copier" and "transpiling" tasks, the option to do a build. See https://github.com/gbochenek/web-app-builder-build

**Comment by kcarrier** [comment]
I for one would be interested in this as well. In my case the downloaded version of a WAB is 15.5 MB. I also use CMV for highly customized projects and using the gruntfile for CMV I am able to get the size of an entire project to 825 KB. It would be nice to use uglify, cssmin, jshint, and compress all files within a WAB project so we know the files being pulled by clients are as small as possible so they load faster.

**Comment by gavinr** [comment]
Closing - superseded by #99
