### ISSUE TITLE
Invalid path (WAB root) message when no apps have been created yet

### ISSUE THREAD

**Issue by hhkaos** [Esri/generator-esri-appbuilder-js#64]
Hi guys, 
Any thoughts why this is happening?
![screenshot 2016-03-22 11 36 49](https://cloud.githubusercontent.com/assets/826965/13948790/66e39724-f022-11e5-8db9-8a178dd22da0.png)

It returns:
```>> Invalid path. Please ensure this is a valid path to your WAB root.```

**Comment by hhkaos** [comment]
I just found the problem myself checking the code of the generator:
```javascript
...
// make sure input directory and apps directory is valid and exists.
var paths = [wabPath, path.join(wabPath, 'server/apps')];
...
```
It was a fresh installation and I need to create at least one app, maybe we should change the log message and also say that "**no 'server/apps/' has been found inside that directory, so please create at least one app**".

**Comment by gavinr** [comment]
I agree this seems to be an issue. I think a short-term solution would be to add that message that you mentioned above. In the long term it would be ideal for the generator to gracefully handle this situation, and simply know that if it looks like we're in the correct WAB directory, allow the user to move forward but they would obviously not be able to choose their app on the next question (so basically automatically picking [none](https://github.com/Esri/generator-esri-appbuilder-js/blob/master/app/index.js#L106-L111) on the next question)

**Comment by tomwayson** [comment]
Renamed from "Invalid path (WAB root) on Mac" to "Invalid path (WAB root) message when no apps have been created yet"
