### ISSUE TITLE
Option for LiveReload

### ISSUE THREAD

**Issue by gavinr** [Esri/generator-esri-appbuilder-js#67]
Using LiveReload is pretty easy, in conjunction with the "watch" Gruntfile task. Should we ask the user if they want to enable this?

**Comment by tomwayson** [comment]
So the grunt task would use something like [grunt-inject](https://www.npmjs.com/package/grunt-inject) to inject the live reload script into the app's index.html [like this example](https://github.com/odoe/esrijs-generator-demo/blob/0101ef747ef5dd3df35dfedbc2f211b511962451/Gruntfile.js#L172-L178)?

**Comment by sebastianmanger** [comment]
If this is still on your radar - I'd appreciate this.
