### ISSUE TITLE
Option to extend from an existing widget

### ISSUE THREAD

**Issue by gavinr** [Esri/generator-esri-appbuilder-js#68]
Many times when creating a new widget, you actually want to extend from an existing widget (Measurement, layer list, etc). Would be nice if that's an option in the generator. 

I hear @gbochenek has been doing some research around this concept ... PRs welcome :) :)

**Comment by tomwayson** [comment]
so:

```
yo esri-appbuilder-js:extend
> What widget would you like to extend?
( ) Annotation
( ) Drawing tools
```
Is that^^^ a list of all included widgets?
Does it generate a widget that _extends_ the built-in widget, or does it make a _copy_ of it?
Would there be more prompts? Is there anything else it would do besides scaffold the new widget files?

**Comment by gavinr** [comment]
Yes that would be a list of all current widgets (in `stemapp/widgets`). Not a copy but instead scaffold out the correct `declare()` and AMD includes that would extend that widget for you.

I think it would still have to ask if you wanted a settings page or not. I think we could assume that if you choose to extend a widget, and also want the settings page, that you want the settings page to be extended too.

**Comment by gbochenek** [comment]
I haven't tried this out without a settings page, however, in the work I've done so far, the settings dialog also prompts the builder to copy our parent widget into the new app, so forcing a settings page scaffold (which inherits from the parent widget's) is most likely the right choice.
