### ISSUE TITLE
Support JSHint 2.9.x - ES Versions

### ISSUE THREAD

**Issue by gavinr** [Esri/generator-esri-appbuilder-js#69]
Per the latest JSHint, we should not be supporting these `.jshintrc` properties:

Code | JSHint
------------ | -------------
https://github.com/Esri/generator-esri-appbuilder-js/blob/master/app/templates/jshintrc#L16 | http://jshint.com/docs/options/#es3
https://github.com/Esri/generator-esri-appbuilder-js/blob/master/app/templates/jshintrc#L46 | http://jshint.com/docs/options/#es5 
https://github.com/Esri/generator-esri-appbuilder-js/blob/master/app/templates/jshintrc#L47 | http://jshint.com/docs/options/#esnext

All of those should be replaced by: [esversion](http://jshint.com/docs/options/#esversion). This should be set to `3`,`5`, or `6` based on the answer to the `Which JavaScript syntax version would you like to develop in?`

**Comment by tomwayson** [comment]
Well, it's complicated.

That whole jshint file comes from the [JSAPI resources](https://github.com/Esri/jsapi-resources/tree/master/jshint). It has ES3 set to true b/c JSAPI 3.x has to support IE8. However, [WAB only supports IE9+](http://doc.arcgis.com/en/web-appbuilder/#supportedBrowsers) and if they're doing 3D then it's [even more restrictive, at least as far as the JSAPI is concerned](https://developers.arcgis.com/javascript/latest/guide/system-requirements/index.html). It doesn't look like the JSAPI team is publishing a .jshintrc for 4.x. I wonder if even use it for 4.x, or use something else like eslint.

The first question is what to do for ES5 3.x (2D) development. I had been previously inclined to just use the JSAPI .jshintrc as is. However, given WAB is IE9+, that .jshintrc is not exactly valid. Ideally we'd use the same .jshintrc file used by the WAB team in that scenario. If we can't get that, then I guess we should drop the ES3 true support.

For ES6 I still think we should do what I suggested (and we didn't do) in #56 - let the user use their linting tool of choice, _and_ don't scaffold a .jshint file at all.

**Comment by gavinr** [comment]
OK, I created this issue because I was using ES6 and the `.jshintrc` was causing me problems. I'll change this issue to let the user use their linting tool of choice (although personally I'd love for the generator to come with one, just because I'm lazy ... maybe we should at least put a message at the end of the generator saying `Since you're using ES6, we didn't install a linting tool. Please see eslint or jshint to setup your configs for that!`?)

**Comment by gavinr** [comment]
Closed in favor of #70
