### ISSUE TITLE
Do not scaffold jshint file

### ISSUE THREAD

**Issue by gavinr** [Esri/generator-esri-appbuilder-js#70]
See related #56 and #69.

**Comment by tomwayson** [comment]
you can probably get your "you should install a linter" message from https://github.com/Esri/generator-esri-appbuilder-js#linting-your-code, or point people there.

**Comment by gavinr** [comment]
@tomwayson after looking through this, I've discovered a problem - the `.jshintrc` is [created in the main generator](https://github.com/Esri/generator-esri-appbuilder-js/blob/master/app/index.js#L294), but the es5-vs-es2015 decision [happens in the widget generator](https://github.com/Esri/generator-esri-appbuilder-js/blob/master/widget/index.js#L119-L122). 

At this point, after reviewing #56 and #69, I'm leaning towards just saying "don't scaffold jshint file" and leave linting up to the user. Sound ok?

**Comment by tomwayson** [comment]
yeah, I think that's the same conclusion I came to.
