### ISSUE TITLE
not a valid path?

### ISSUE THREAD

**Issue by Ricardh522** [Esri/generator-esri-appbuilder-js#72]
I've used this tool with previous versions of WAB, but recently I get an error when specifying the path to the WAB root.  I've tried all the combinations of root locations; drive letters; directory names; but nothing seems to work.  

I've not looked at the source code yet to see if you are catching an error that I am not aware of but I'd like to go ahead and submit this request for a possible bug.

**Comment by gavinr** [comment]
What version of WAB are you using?



-- 
--
http://gavinr.com

**Comment by Ricardh522** [comment]
The newest version 2.1.  One thing I thought of that I did not try is to put double quotes around my path, but since there are no spaces in it, it was not something I thought of at the time.  I am using windows 10.

**Comment by gavinr** [comment]
Hi Richard,

I just tested with the latest version of WAB and it seems to work fine for me. I'm on Windows 7. Can you please post the error message you're getting, or a screenshot?

Thanks!

**Comment by tomwayson** [comment]
Possible permissions issue?

**Comment by Ricardh522** [comment]
![enteringpath](https://cloud.githubusercontent.com/assets/5625223/17138122/cc6fca8e-530c-11e6-9807-999594b7330b.PNG)
![invalidpath](https://cloud.githubusercontent.com/assets/5625223/17138125/cf84c602-530c-11e6-9d2d-e6b3ab4f2398.PNG)

The initial attempts I made to use the tool were on my home PC where Node 4.4.7 is installed on the G drive separate from my operating system on C.  In order to eliminate that as an issue for permission reasons, I am now doing the tests on my work pc which has only one drive C:\\.  

What I did just now was extract the WAB zip file to generate the WebAppBuilderForArcGIS folder and moved it into a folder named WAB at the C:\\ root.  I get issues with the file path names being too long if the WebAppBuilderForArcGIS folder is located somewhere deeper in my path, like the user path.  Next I create a src folder in the WAB folder as a sibling to the WebAppBuilderForArcGIS folder.  I cd into the src folder and run the generator after first create a package.json file.  The first time I ran the  generator it created a jshint file, widget folder, and a theme folder, but did not generate the gruntfile nor did it run through the steps asking about the type of widget to create.  It is not reproducing that behavior anymore now that I deleted the output created and am running the generator again.

I gotta get back on some tasks for reviewing docs here at the office, but I will be available to try this throughout the day.

Thanks,

Richard

**Comment by tomwayson** [comment]
Thanks for the detailed info. In the scenario you describe, you should enter "c:\WAB\ WebAppBuilderForArcGIS" when prompted for the WAB root (not "c:\\WAB\\ WebAppBuilderForArcGIS"

**Comment by Ricardh522** [comment]
This is the path to my web app builder directory as copied from the explorer path browser: C:\WAB\WebAppBuilderForArcGIS

**Comment by tomwayson** [comment]
Yes. So if you use that, does it work?

**Comment by tomwayson** [comment]
I've updated my comment above b/c it looks like GitHub's markdown was not showing the `\\`. Essentially, I think the double backslashes in your screenshot above are the problem.

**Comment by Ricardh522** [comment]
![enteringpath](https://cloud.githubusercontent.com/assets/5625223/17141839/c363367e-531b-11e6-8d7d-e87e5916b9ec.PNG)
![invalidpath](https://cloud.githubusercontent.com/assets/5625223/17141847/c49a0e3c-531b-11e6-8f61-273f0230163b.PNG)

The above images show that the path with single backslash does not work.  

I like your idea about it being a permissions issue.  This laptop was recently updated to Windows 10, and since then I have updated my node.js to 4.4.7.  

I've just ran the command prompt as admin and the results were the same.

**Comment by tomwayson** [comment]
I wonder if this is at all related to #64

Have you created any WAB apps yet?

What version of generator-esri-appbuilder-js do you have installed? You can run `npm ls -g --depth=0` to see the version.

**Comment by Ricardh522** [comment]
That is exactly the problem.  It works great now that I first create an app to generate the apps directory to satisfy the 'server/apps' string in the verify function of the generator.

**Comment by tomwayson** [comment]
Re-opening as a reminder until the fix for this lands in a release.

**Comment by gavinr** [comment]
This should be resolved in [v2.1.1](https://github.com/Esri/generator-esri-appbuilder-js/releases/tag/v2.1.1). Thanks for the report @Ricardh522!
