### ISSUE TITLE
Update for WAB 2.2

### ISSUE THREAD

**Issue by gavinr** [Esri/generator-esri-appbuilder-js#75]
[v2.1 of Web AppBuilder was released recently](https://blogs.esri.com/esri/arcgis/2016/07/19/web-appbuilder-for-arcgis-v2-1-developer-edition-now-available/). We should update `wabVersion` to reflect the latest.

Edit: [v2.2 is out](https://blogs.esri.com/esri/arcgis/2016/10/12/web-appbuilder-for-arcgis-v2-2-developer-edition-now-available/)

**Comment by tomwayson** [comment]
https://github.com/Esri/generator-esri-appbuilder-js/blob/68be02fd8fe662a47ee5fd6192e88538fbaec3be/widget/index.js#L139-L142
