### ISSUE TITLE
Should support "closeable" manifest property

### ISSUE THREAD

**Issue by gavinr** [Esri/generator-esri-appbuilder-js#76]
See explanation of `closeable` [here](https://developers.arcgis.com/web-appbuilder/guide/in-panel-and-off-panel-widget.htm).

We should either ask the user if they want it to be closeable or not, or infer it from other answers (I'm not sure of the exact algorithm ... maybe that's something we can discuss?)

**Comment by tomwayson** [comment]
I guess we could have an additional prompt and use  [a when function](https://github.com/Esri/generator-esri-appbuilder-js/blob/8389b586d41a6bad4130b11be0ecc8e571df9359/widget/index.js#L87-L89) to check if `inPanel` is `false`, right?

**Comment by gavinr** [comment]
Closing this issue - no community interest and this particular property is no more notable than other properties we're not including. Will leave it up to the developer to add the `closeable` property if so desired.
