### ISSUE TITLE
Update to WAB 2.3

### ISSUE THREAD

**Issue by tomwayson** [Esri/generator-esri-appbuilder-js#82]
once that is released (late Jan 2017). just a reminder.

**Comment by tomwayson** [comment]
FYI - I have tested [current master](https://github.com/Esri/generator-esri-appbuilder-js/tree/44854f3ac421686f9d9225b2df9c1772ea8b2caf) against 2.3 and it works perfectly.

I think the only thing to do here is to update the manifest template.

Also, while we're at it, the behavior in [these lines](https://github.com/Esri/generator-esri-appbuilder-js/blame/44854f3ac421686f9d9225b2df9c1772ea8b2caf/app/index.js#L71-L75) struck me as odd. @jPurush and @gavinr, not sure if either of you remember the resoning there, but it seems to me that at this point, the WAB root folder should always default to  `path.join(homedir, 'WebAppBuilderForArcGIS');`. Maybe in previous downloads that was the name of the folder, but no one can access those downloads anymore, you just get the latest, which always names the folder "WebAppBuilderForArcGIS". If you agree, I say we make that part of the PR for this issue.

**Comment by tomwayson** [comment]
I guess it's not the manifest template itself that gets updated. See this PR for needed changes: https://github.com/Esri/generator-esri-appbuilder-js/pull/78/files

**Comment by jPurush** [comment]
I think it was to keep the 1.3 support for 2d at that time but add 3d functionality. I see a related issue [here](https://github.com/Esri/generator-esri-appbuilder-js/issues/55). And I didn't tie the default 2d folder to WABVersion, so it has persisted. Good catch! I agree that there isn't any need for conditional WAB root folders.
