### ISSUE TITLE
babel-core

### ISSUE THREAD

**Issue by ahmed-abdelmotey** [Esri/generator-esri-appbuilder-js#90]
currently when i run grunt it throws an error for babel-core module not found, installing babel-core solves the problem.

**Comment by gavinr** [comment]
@ahmed-abdelmotey thanks for the report. A few questions:

1. What version of yeoman are you using? (run `yo --version`)
2. What version of npm are you using? (run `npm -v`)
3. What version of nodejs are you using? (run `node -v`)
4. What OS version are you on?
5. What settings are you using when going through the Yeoman generator?

Thanks!

**Comment by ahmed-abdelmotey** [comment]
**used versions:** 
**yeoman :** 2.0.0
**npm:** 3.10.10
**node:** v6.11.0
**OS:** windows 10 pro 64x
**yeoman settings:** 
`{
  "generator-esri-appbuilder-js": {
    "widgetsType": "is2d",
    "useSass": true
  }
}`
**widget sub generator:**

- selected features : all
- setting page: yes
- setting page features: all
- javascript version: ES2015

**Comment by gavinr** [comment]
@ahmed-abdelmotey I have very similar setup, other than NPM version (I am on v5.3.0) - I tested and things seem to work OK without the `babel-core` error. I will try to test on a separate machine, ideally with `npm v3`, in the future, and will let you know if I get the error in that case.

**Comment by kenbuja** [comment]
After getting this error, I used this command to install babel-loader

`npm install babel-core babel-loader --save-dev`

and it worked properly.

**Comment by tomwayson** [comment]
This is fixed in [v2.2.1](https://github.com/Esri/generator-esri-appbuilder-js/releases/tag/v2.2.1)
